// SVG Icon components - all icons are pure SVG, no emojis
export { HomeIcon } from "./home-icon"
export { DiaryIcon } from "./diary-icon"
export { ProgressIcon } from "./progress-icon"
export { ProfileIcon } from "./profile-icon"
export { PlusIcon } from "./plus-icon"
export { CameraIcon } from "./camera-icon"
export { UploadIcon } from "./upload-icon"
export { ChevronDownIcon } from "./chevron-down-icon"
export { ChevronUpIcon } from "./chevron-up-icon"
export { TrashIcon } from "./trash-icon"
export { SettingsIcon } from "./settings-icon"
export { LogoutIcon } from "./logout-icon"
export { AppleIcon } from "./apple-icon"
export { BurgerIcon } from "./burger-icon"
export { SaladIcon } from "./salad-icon"
export { CupIcon } from "./cup-icon"
